### ISSUE TITLE
This plugin is unuseful when running 'vite build' command. How to resolve?

### ISSUE THREAD

**Issue by Hemingway-AT** [williamyorkl/vite-plugin-vue2-suffix#3]
![error](https://user-images.githubusercontent.com/52380703/178404796-efea97b9-1a1e-4cd0-8530-ca9df28ef0d6.png)
It's useful on server environment. However, as above, lack of suffix happends when executing build script.

**Comment by williamyorkl** [comment]
> ![error](https://user-images.githubusercontent.com/52380703/178404796-efea97b9-1a1e-4cd0-8530-ca9df28ef0d6.png) It's useful on server environment. However, as above, lack of suffix happends when executing build script.

Hi there, as the vite build is still unstable, so this plugin is only a replacement on vite dev mode, the build option we suggest webpack instead.
